server:
  port: 4001
spring:
  datasource:
    url: jdbc:hsqldb:mem:webrobot-lookup-definition-schedule
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.HSQLDialect
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        lookup-jobs:
          content-type: application/json
        new-lookup-definitions:
          group: lookup-definition-schedule-service
        new-lookups:
          group: lookup-definition-schedule-service
logging:
  level: 
    root: info
      
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/webrobot-lookup-definition-schedule
    username: webrobot
    password: aKSXHHxZDxs7sNaW
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
